version: '3.8'

services:
  chat-app:
    image: chat-app-image
    ports:
      - "3002:3002"
    environment:
      - PG_URL=postgres://POSTGRES_USER:POSTGRES_PASSWORD@chat-app:5432/chat-app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: la1234
      POSTGRES_DB: chat-app
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 

volumes:
  postgres-data:
    driver: local
