version: '3.8'

services:
  chat-app:
    image: chat-app-image
    ports:
      - "3002:3002"
    environment:
      PG_URL: postgres://postgres:la1234@db:5432/chat-app
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: la1234
      POSTGRES_DB: chat-app
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
