version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      PG_URL: postgres://postgres:la1234@db:5432/chat-app
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: la1234
      POSTGRES_DB: chat-app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
